### PR TITLE
Update envtpl.py

### PR DESCRIPTION
**Pull request by haithem2**
Add UTF8 encoding support

### CODE REVIEW

**Comment by haithem2** [comment]
@andreasjansson could you please check my modification ?
It works only for python 2.7

**Comment by haithem2** [comment]
I added a fix and the build pass sucessfully.

**Comment by haithem2** [comment]
@andreasjansson could you please verify/accept my PR asap.
Thank You.

**Comment by hardware** [comment]
It would be great if this pull request could be merged. @andreasjansson Do you still maintain this project ?

@haithem2 : Otherwise, I found another cli program working with UTF-8 : https://github.com/noqcks/gucci

**Comment by andreasjansson** [comment]
Thanks very much for this @haithem2! And apologies for the delay. I guess I do maintain this project, but I don't really use it myself anymore so I sometimes forget to check PRs and issues. I'll try to keep up with it better!

**Comment by hardware** [comment]
@andreasjansson  when this change will be available with python-pip ?

**Comment by andreasjansson** [comment]
@hardware it's uploaded now as 0.6.0 https://pypi.python.org/pypi/envtpl

**Pull request merged**
